### ISSUE TITLE
Getting an error on stateManager.changeState in menuState processEvents loop

### ISSUE THREAD

**Issue by maximaexchen** [aclonegeek/SSM#3]
Hi. 
When I change the state in menuState to switch to gameState in the while loop of processEvents method, the loop runs once again in menuState instead of new gameState and so I get "Access violation while reading at position..."

I needed to set a "return" instead of "break" in the switch-case block to get it work properly.

regards marcus

**Comment by aclonegeek** [comment]
Hi @maximaexchen!

Thanks for the report. It looks like all of the breaks in `GameState::processEvents()` and `MenuState::processEvents()` should be returns instead as you mentioned. Would you like to open a PR to correct it?

**Comment by aclonegeek** [comment]
Fixed by #4.
